import { TechSkill } from './schema';

export const techStack: TechSkill[] = [
    { src: "/h.png", alt: "HTML", name: "HTML" },
    { src: "/c.png", alt: "CSS", name: "CSS" },
    { src: "/js.png", alt: "JavaScript", name: "JavaScript" },
    { src: "/ts.png", alt: "TypeScript", name: "TypeScript" },
    { src: "/nodejs.png", alt: "Node.js", name: "Node.js" },
    { src: "/npm.png", alt: "npm", name: "npm" },
    { src: "/nextjs.png", alt: "Next.js", name: "Next.js" },
    { src: "/tailwind.png", alt: "Tailwind CSS", name: "Tailwind CSS" },
    { src: "/shadcn.png", alt: "shadcn", name: "shadcn" },
    { src: "/py.png", alt: "Python", name: "Python" },
    { src: "/st.png", alt: "Streamlit", name: "Streamlit" },
    { src: "/ch.png", alt: "Chainlit", name: "Chainlit" },
    { src: "/openai.png", alt: "OpenAI SDK", name: "OpenAI SDK" },
    { src: "/gemini.png", alt: "Gemini API", name: "Gemini API" },
    { src: "/firebase.png", alt: "Firebase", name: "Firebase" },
    { src: "/netlify.png", alt: "Netlify", name: "Netlify" },
    { src: "/sanityLogo.png", alt: "Sanity CMS", name: "Sanity CMS" },
    { src: "/stripe.svg", alt: "Stripe", name: "Stripe" },
    { src: "/Fastapi.svg", alt: "Fastapi", name: "Fastapi" },
    { src: "/Neon.png", alt: "Neon", name: "Neon" },
    { src: "/docker.png", alt: "docker", name: "Docker" },
    { src: "/kubernetes.png", alt: "kubernetes", name: "kubernetes" },
    { src: "/claudecode.png", alt: "claude code", name: "claude code" },
    { src: "/hf-logo.svg", alt: "Hugging Face", name: "Hugging Face" },
    { src: "/docusaurus.png", alt: "docussarus", name: "docussarus" },
    { src: "/better-auth.png", alt: "better-auth", name: "better-auth" },
    { src: "/mcp.png", alt: "mcp", name: "mcp servers" },
];