FROM nginx:alpine

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the UI files to nginx html directory
COPY UI/ /usr/share/nginx/html/

#Nginx in the nginx:alpine image always listens on port 80.
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]